name: langgraph_env
channels:
  - defaults
dependencies:
  - python=3.10  # or any version you prefer
  - notebook
  - ipykernel
  - pip
  - pip:
    - azure-ai-projects==1.0.0
    - azure-identity==1.23.1
    - python-dotenv==1.1.1
    - langgraph==0.6.2
    - langchain==0.3.27
    - langchain-openai==0.3.28
    - fastapi==0.116.1
    - uvicorn==0.35.0